name: GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  COURSIER_REPOSITORIES: central|https://s01.oss.sonatype.org/content/repositories/snapshots|jitpack|https://corporate.com/repo

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'
      - run: chmod +x millw
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-unknown-linux-gnu
          override: true
      - run: cargo install cross
      - run: cd mionative/native && cargo build --release --target x86_64-unknown-linux-gnu
      - run: cd mionative/native && cross build --release --target x86_64-apple-darwin
      - run: cd mionative/native && cross build --release --target x86_64-pc-windows-msvc
      - run: cd mionative/native && cross build --release --target aarch64-apple-darwin